-- Last Update: 09.04.2020

local mountList = {
	'Xmas Dragonite Mount',
	'Bicycle',
	'Red Bicycle',
	'Blue Bicycle',
	'Green Bicycle',
	'Yellow Bicycle',
	'Ariados Mount',
	'S Ariados Mount',
	'Venusaur Mount',
	'S Venusaur Mount',
	'Delcatty Mount',
	'S Delcatty Mount',
	'Haunter Mount',
	'S Haunter Mount',
	'Lycanroc Mount',
	'S Lycanroc Mount',
	'Espeon Mount',
	'S Espeon Mount',
	'Muk Mount',
	'S Muk Mount',
	'Mareep Mount',
	'S Mareep Mount',
	'Liepard Mount',
	'S Liepard Mount',
	'Aurorus Mount',
	'S Aurorus Mount',
	'Luxray Mount',
	'S Luxray Mount',
	'Talonflame Mount',
	'S Talonflame Mount',
	'Togekiss Mount',
	'S Togekiss Mount',
	'Charizard Mount',
	'S Charizard Mount',
	'Rapidash Mount',
	'S Rapidash Mount',
	'Aerodactyl Mount',
	'S Aerodactyl Mount',
	'Sylveon Mount',
	'S Sylveon Mount',
	'Umbreon Mount',
	'S Umbreon Mount',
	'Fearow Mount',
	'S Fearow Mount',
	'Latios Mount',
	'Latias Mount',
	'Absol Mount',
	'S Absol Mount',
	'Dodrio Mount',
	'S Dodrio Mount',
	'Glaceon Mount',
	'S Glaceon Mount',
	'Stantler Mount',
	'S Stantler Mount',
	'Houndoom Mount',
	'S Houndoom Mount',
	'Manectric Mount',
	'S Manectric Mount',
	'Ninetales Mount',
	'S Ninetales Mount',
	'Arcanine Mount',
	'S Arcanine Mount',
}

return mountList